security:
    encoders:
        App\Entity\Mydb\Admin:
            algorithm: bcrypt
        App\Entity\Petdb\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: null }
        db_provider: 
            entity:
                class: App\Entity\Mydb\Admin
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy

            form_login:
                login_path: login
                check_path: login
                provider: db_provider
                username_parameter: _username
                password_parameter: _password
                default_target_path: /dashboard

            logout:
                path: /logout
                target: /


    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        # - { path: ^/profile, roles: ROLE_ADMIN }
        
